### ISSUE TITLE
Sticky header with collectionview

### ISSUE THREAD

**Issue by douglasalexandre** [ashfurrow/ARCollectionViewMasonryLayout#33]
Hey @ashfurrow @orta !! I here again! 😄 

There is some example in swift to create Sticky Headers in collectionview use this framework `ARCollectionViewMasonryLayout` ?

**Comment by ashfurrow** [comment]
Nothing in Swift I'm afraid, we don't use the sticky headers very often, only [in this file](https://github.com/artsy/eigen/blob/505b08c70f58d703f19436bc41975b84b052643e/Artsy/View_Controllers/Embedded/Generics/AREmbeddedModelsViewController.m). If you follow Apple's guidelines for working with UICollectionViews' supplementary views, it should be straightforward to use in Swift. Good luck 👍
