### ISSUE TITLE
Fixed header/footer views support

### ISSUE THREAD

**Issue by jlee0831** [ashfurrow/ARCollectionViewMasonryLayout#34]
The docs in the README appear to be out of date. I can't seem to find any references to the method `- (CGFloat)collectionView:(UICollectionView *)collectionView layout:(ARCollectionViewMasonryLayout *)collectionViewLayout dimensionForHeaderAtIndexPath:(NSIndexPath *)indexPath` anywhere in the current version of the code.

Is there no longer support for header/footer views, or is there now a different way to add them?

**Comment by ashfurrow** [comment]
Good catch! Looks like they were removed in https://github.com/ashfurrow/ARCollectionViewMasonryLayout/pull/16 , but they're still supported! We just use the standard UICollectionViewFlowLayout method of using headers/footers. I'll update the readme.
